# Generated by Django 3.1 on 2020-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_link', models.TextField(verbose_name='Старая ссылка')),
                ('new_link', models.TextField(verbose_name='Новая ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
