# Generated by Django 3.1 on 2020-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200810_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable')], default='fruit', max_length=20)),
                ('img', models.ImageField(default='no_image.png', upload_to='product_image')),
            ],
        ),
    ]
