# Generated by Django 3.1 on 2020-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable')], default='fruit', max_length=20),
        ),
    ]
