# Generated by Django 3.1 on 2020-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200819_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='product_image', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable')], default='fruit', max_length=20),
        ),
    ]
