# Generated by Django 3.1 on 2020-08-25 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20200821_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('payment_state', models.CharField(max_length=100, verbose_name='Статус оплаты')),
                ('email', models.EmailField(max_length=250, verbose_name='Емеил')),
                ('number_phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date_order', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.DetailsOrder'),
        ),
    ]
